CREATE TABLE employee (
    employeeId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName varchar(20),
lastName varchar(20),
patronymic varchar(20),
position varchar(20)
);

CREATE TABLE project (
projectId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(30),
shortTitle varchar(15),
description varchar(50)
);
 
CREATE TABLE task (
    taskId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeId INT,
    projectId INT,
    title varchar(30),
duration int,
startDate date,
endDate date,
status varchar(15),
    FOREIGN KEY(employeeId) REFERENCES employee(employeeId),
FOREIGN KEY(projectId) REFERENCES project(projectId)
);
